import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// Inconsolata
import { Inconsolata } from "next/font/google";
import "./globals.css";
import Header from "@/components/headers/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"], weight: ["300", "500"] });
const inconsolata = Inconsolata({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Cloud Hosting",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <Header />
        <ToastContainer
          position="top-center"
          theme="colored"
          autoClose={2000}
        />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
